[FA] First draft of CH2/P3
huggingface/course pull request #140
Opened 2022-04-23 14:08 UTC by jowharshamshiri

Translated CH2/P3
Additions to G.

@hamedonline please review. ❤️

Related to https://github.com/huggingface/course/issues/50

2022-04-23 14:21 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/course/course/pr_140). All of your documentation changes will be reflected on that endpoint.

2022-04-23 16:43 UTC, hamedonline commented
> Translated CH2/P3 Additions to G.
> 
> @hamedonline please review. ❤️
> 
> Related to #50

Great work ❤️, thanks @jowharshamshiri aziz.
Will do my best tonight :)

2022-04-24 10:00 UTC, hamedonline commented on chapters/fa/chapter2/3.mdx
> +در این بخش نگاهی نزدیکتر به ساخت و استفاده از مدل‌ها می‌اندازیم. کلاس `AutoModel` را به کار خواهیم گرفت که برای ساختن مدل‌ها از نقطه‌های تعلیم مشخص بسیار پرکاربرد است.
`نزدیکتر`

I think we'd better use 'نزدیک‌تر' per style guide's saying.

![tar](https://user-images.githubusercontent.com/24595790/164967951-4ac9fb9a-afd8-4f5b-8304-2bf089f503a8.jpg)

I'd also consider a comma in this sentence for an easier read:
"... که برای ساختن مدل‌ها از نقطه‌های تعلیم مشخص، بسیار پرکاربرد است."

2022-04-24 10:01 UTC, hamedonline commented on chapters/fa/chapter2/3.mdx
> +با وجود اینکه هنوز ندیده‌اید تک تک این ویژگی‌ها چه تاثیری دارند، بعضی از آنها برای شما آشنا هستند: ویژگی `hidden_size` اندازه بردار `hidden_states` را مشخص می‌کند و ویژگی `num_hidden_layers` مشخص کنن
"لابه‌های" -> "لایه‌های"

2022-04-24 10:01 UTC, hamedonline commented on chapters/fa/chapter2/3.mdx
> +ساختن مدل با تنظیمات پیش‌فرض، باعث پرشدن آن با اعداد تصادفی می‌شود.
What do you think of this instead?
"باعث مقداردهی اولیه (وزن‌های) آن با اعداد تصادفی می‌شود"

2022-04-24 10:01 UTC, hamedonline commented on chapters/fa/chapter2/3.mdx
> +همان طور که قبلا دیدید، می‌توانیم کلاس `BertModel` را با کلاس معادل `AutoModel` جایگزین کنیم. از این پس همین کار را خواهیم کرد چون به این صورت کد وابسته به نقطه تعلیم خاصی نخواهد بود. اگر کد شما با ی
`به مسئله مشابهی(برای مثال تحلیل احساسات)`
there is a missing space before parentheses opening, should be changed to:
"... به مسئله مشابهی (برای مثال تحلیل احساسات)"

2022-04-24 10:01 UTC, hamedonline commented on chapters/fa/chapter2/3.mdx
> +این مدل اکنون با وزون نقطه تعلیم پر شده است و می‌توان آن را مستقیماً برای مسائلی که برای آن تعلیم دیده به کار برد یا برای مسئله جدیدی کوک کرد. با تعلیم روی وزون از پیش تعلیم دیده جای تعلیم از صفر، می
The plural of "وزن" in "وزون"  form feels very alien to me. What do you think of this suggestion instead:
این مدل اکنون با تمامی وزن‌های نقطه تعلیم راه‌اندازی شده است

Also addition of a comma and half-space:
... برای مسائلی که برای آن تعلیم دیده به کار برد، یا برای مسئله جدیدی کوک کرد. با تعلیم روی وزن‌های از پیش تعلیم دیده، به جای تعلیم از صفر، می‌توانیم به سرعت به نتایج خوبی دست پیدا کنیم.

2022-04-24 10:02 UTC, hamedonline commented on chapters/fa/chapter2/3.mdx
> +این وزون دانلود و در پوشه‌ای مخصوص ذخیره شده‌اند، تا اجرای تابع `from_pretrained()` در آینده مسبب دانلود دوباره‌اشان نباشد. این پوشه به صورت پیش‌فرض در آدرس *~/.cache/huggingface/transformers* قرار د
"دوباره‌اشان" -> "دوباره‌شان"
Also another substitute suggestion for "cache" here:
این وزن‌ها دانلود و در پوشه‌ای مخصوص انبار شده‌اند...

2022-04-24 10:02 UTC, hamedonline commented on chapters/fa/chapter2/3.mdx
> +اگر نگاهی به فایل *config.json* بیاندازید، با ویژگی‌های آشنای مورد نیاز برای ساختن معماری مدل روبرو خواهید شد. این فایل حاوی مقادیری متادیتا، مانند نقطه مادر این نقطه تعلیم و نسخه‌‌ کتابخانه ترنسفورم
I think the second part of this paragraph could be improved; a sample suggestion:
این فایل حاوی مقادیری متادیتا همچون نقطه مادر این نقطه تعلیم، و نسخه‌‌ کتابخانه ترنسفورمرهای هاگینگ‌فِیس که آخرین بار برای ذخیره‌سازی این نقطه به کار رفته است، می‌باشد.

2022-04-24 10:02 UTC, hamedonline commented on chapters/fa/chapter2/3.mdx
> +فایل *tf_model.h5* در واقع *دیکشنری وضعیت‌ها* است و حاوی تمام وزون مدل شماست. این دو فایل به همراه هم کاربرد دارند؛ فایل تنظیمات برای دانستن معماری به کار رفته در مدل نیاز است و پارامترهای مدل هم که
suggestion:
... فایل تنظیمات، که برای اطلاع از معماری به کار رفته در مدل ضروریست، و وزن‌های مدل که در اصل پارامترهای مدل شما هستند.

2022-04-24 10:02 UTC, hamedonline commented on chapters/fa/chapter2/3.mdx
> +این تابع آرگومان‌های بسیاری را می‌پذیرد ولی تنها شناسه‌های ورودی ضروری هستند. کاربرد آرگومان‌های دیگر و شرایط ضرورت آنها را بعد توضیح خواهیم داد. ولی ابتدا باید نگاهی نزدیکتر به توکِنایزرهایی که ورود
`نزدیکتر` -> `نزدیک‌تر`

2022-04-24 10:05 UTC, hamedonline requested changes
Fantastic job overall ❤️

2022-04-24 21:33 UTC, hamedonline commented on chapters/fa/chapter2/3.mdx
> +توکِنایزر این جملات را به اندیس‌های مخصوص کلمات که معمولا به آنها *شناسه‌های ورودی* می‌گوییم، تبدیم می‌کند. هر رشته اکنون لیستی از اعداد است! نتیجه خروجی از این قرار است:
`تبدیم` -> `تبدیل`

2022-04-25 01:56 UTC, jowharshamshiri commented on chapters/fa/chapter2/3.mdx
> +در این بخش نگاهی نزدیکتر به ساخت و استفاده از مدل‌ها می‌اندازیم. کلاس `AutoModel` را به کار خواهیم گرفت که برای ساختن مدل‌ها از نقطه‌های تعلیم مشخص بسیار پرکاربرد است.
Fixed.

2022-04-25 01:56 UTC, jowharshamshiri commented on chapters/fa/chapter2/3.mdx
> +با وجود اینکه هنوز ندیده‌اید تک تک این ویژگی‌ها چه تاثیری دارند، بعضی از آنها برای شما آشنا هستند: ویژگی `hidden_size` اندازه بردار `hidden_states` را مشخص می‌کند و ویژگی `num_hidden_layers` مشخص کنن
typo. fixed.

2022-04-25 01:59 UTC, jowharshamshiri commented on chapters/fa/chapter2/3.mdx
> +ساختن مدل با تنظیمات پیش‌فرض، باعث پرشدن آن با اعداد تصادفی می‌شود.
Agree. Fixed.

2022-04-25 02:00 UTC, jowharshamshiri commented on chapters/fa/chapter2/3.mdx
> +همان طور که قبلا دیدید، می‌توانیم کلاس `BertModel` را با کلاس معادل `AutoModel` جایگزین کنیم. از این پس همین کار را خواهیم کرد چون به این صورت کد وابسته به نقطه تعلیم خاصی نخواهد بود. اگر کد شما با ی
Is it tho?

2022-04-25 02:06 UTC, jowharshamshiri commented on chapters/fa/chapter2/3.mdx
> +این مدل اکنون با وزون نقطه تعلیم پر شده است و می‌توان آن را مستقیماً برای مسائلی که برای آن تعلیم دیده به کار برد یا برای مسئله جدیدی کوک کرد. با تعلیم روی وزون از پیش تعلیم دیده جای تعلیم از صفر، می
The plural felt weird to me too. Changed all instances.

What half-space?

2022-04-25 02:14 UTC, jowharshamshiri commented on chapters/fa/chapter2/3.mdx
> +این وزون دانلود و در پوشه‌ای مخصوص ذخیره شده‌اند، تا اجرای تابع `from_pretrained()` در آینده مسبب دانلود دوباره‌اشان نباشد. این پوشه به صورت پیش‌فرض در آدرس *~/.cache/huggingface/transformers* قرار د
Style guide doesn't mention what to do with "e-shan" when word ends in "he". This seems fine to me. Also googled it, a lot of people using it.

Ok changing to anbar and adding to G.

2022-04-25 02:40 UTC, jowharshamshiri commented on chapters/fa/chapter2/3.mdx
> +اگر نگاهی به فایل *config.json* بیاندازید، با ویژگی‌های آشنای مورد نیاز برای ساختن معماری مدل روبرو خواهید شد. این فایل حاوی مقادیری متادیتا، مانند نقطه مادر این نقطه تعلیم و نسخه‌‌ کتابخانه ترنسفورم
The comma before AND is a bad idea.

Added the extra verb at the end.

2022-04-25 02:49 UTC, jowharshamshiri commented on chapters/fa/chapter2/3.mdx
> +فایل *tf_model.h5* در واقع *دیکشنری وضعیت‌ها* است و حاوی تمام وزون مدل شماست. این دو فایل به همراه هم کاربرد دارند؛ فایل تنظیمات برای دانستن معماری به کار رفته در مدل نیاز است و پارامترهای مدل هم که
Please don't put commas before your ANDs.

Changed "نیاز" to "ضروری", better word thanks for the suggestion.

On the second part about weights in the file, my version is closer to the original text. Yours also repeats the word model twice.

2022-04-25 02:49 UTC, jowharshamshiri commented on chapters/fa/chapter2/3.mdx
> +این تابع آرگومان‌های بسیاری را می‌پذیرد ولی تنها شناسه‌های ورودی ضروری هستند. کاربرد آرگومان‌های دیگر و شرایط ضرورت آنها را بعد توضیح خواهیم داد. ولی ابتدا باید نگاهی نزدیکتر به توکِنایزرهایی که ورود
Fixed.

2022-04-25 02:50 UTC, jowharshamshiri commented on chapters/fa/chapter2/3.mdx
> +توکِنایزر این جملات را به اندیس‌های مخصوص کلمات که معمولا به آنها *شناسه‌های ورودی* می‌گوییم، تبدیم می‌کند. هر رشته اکنون لیستی از اعداد است! نتیجه خروجی از این قرار است:
Typo. Fixed.

2022-04-25 02:55 UTC, jowharshamshiri commented
> Fantastic job overall heart

Just trying to not let you and the peeps down! heart emoji back at you.

2022-04-25 03:11 UTC, jowharshamshiri commented
> Fantastic job overall heart

@hamedonline jan please approve changes if you think it's done.

2022-04-25 04:03 UTC, jowharshamshiri commented
> Fantastic job overall heart

@hamedonline jan, applied your notes please check.

2022-04-25 08:15 UTC, lewtun reviewed
Awesome job @jowharshamshiri and @schoobani ❤️ ! Just ping me when you think this is ready to be merged - structurally it all looks good on my side 🚀

2022-04-25 08:21 UTC, hamedonline commented on chapters/fa/chapter2/3.mdx
> +همان طور که قبلا دیدید، می‌توانیم کلاس `BertModel` را با کلاس معادل `AutoModel` جایگزین کنیم. از این پس همین کار را خواهیم کرد چون به این صورت کد وابسته به نقطه تعلیم خاصی نخواهد بود. اگر کد شما با ی
> Should there be tho?

I believe so.

![par](https://user-images.githubusercontent.com/24595790/165049345-20d34711-0ce5-46b9-8d3a-7650694a971e.jpg)

2022-04-25 08:23 UTC, hamedonline commented on chapters/fa/chapter2/3.mdx
> +این مدل اکنون با وزون نقطه تعلیم پر شده است و می‌توان آن را مستقیماً برای مسائلی که برای آن تعلیم دیده به کار برد یا برای مسئله جدیدی کوک کرد. با تعلیم روی وزون از پیش تعلیم دیده جای تعلیم از صفر، می
By half-space I was referring to "می توانیم".

2022-04-25 08:27 UTC, hamedonline commented on chapters/fa/chapter2/3.mdx
> +این مدل اکنون با وزن‌های نقطه تعلیم پر شده است و می‌توان آن را مستقیماً برای مسائلی که برای آن تعلیم دیده به کار برد یا برای مسئله جدیدی کوک کرد. با تعلیم روی وزن‌های از پیش تعلیم دیده، به جای تعلیم
`می توانیم` -> `می‌توانیم`

2022-04-25 08:30 UTC, hamedonline approved these changes
Please just apply the small fix for "می توانیم" dear @jowharshamshiri and after that we're good to go @lewtun ❤️

2022-04-25 09:58 UTC, jowharshamshiri commented
> Please just apply the small fix for "می توانیم" dear @jowharshamshiri and after that we're good to go @lewtun heart

Thanks for the review @hamedonline jan and @lewtun please merge.

2022-04-25 10:09 UTC, hamedonline approved these changes

2022-04-25 10:35 UTC, jowharshamshiri commented
@letwun The checks seem to be failing... looking into it.

2022-04-26 19:27 UTC, merged

2022-04-26 19:27 UTC, lewtun commented
Thank you very much for the contribution @jowharshamshiri  and thank you @hamedonline for the review!