[PT][Chapter 01 - 2.mdx] - issue #51
huggingface/course pull request #170
Opened 2022-05-08 18:47 UTC by victorescosta

issue #51

2022-05-08 19:05 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/course/course/pr_170). All of your documentation changes will be reflected on that endpoint.

2022-05-14 15:58 UTC, johnnv1 requested changes

2022-05-14 15:58 UTC, johnnv1 commented on chapters/pt/chapter1/2.mdx
> +- **Generating a new sentence from an input text**: Translating a text into another language, summarizing a text
Faltou esse tópico

2022-05-14 15:58 UTC, johnnv1 commented on chapters/pt/chapter1/2.mdx
> +NLP não se limita ao texto escrito. Também abarca desafios complexos nos campos de reconhecimento de discurso e visão computacional, tal como a geração de transcrição de uma amostra de áudio ou a des
Também **engloba**...

2022-05-16 14:33 UTC, lewtun reviewed
Thanks for this translation @victorescosta 🚀 !!

Would you like to integrate the suggestions from @johnnv1 and then we can merge?

2022-05-16 18:19 UTC, victorescosta reviewed
Thank you, meu caro!

2022-05-16 18:29 UTC, victorescosta reviewed
All done!

2022-05-17 04:20 UTC, lewtun approved these changes
Thanks for iterating - this looks great 🔥 !

2022-05-17 04:20 UTC, merged