Translation chapter 8 in Russian lang is complete
huggingface/course pull request #667
Opened 2024-01-27 10:08 UTC by pdumin

Also small fix in chapter 5 section 3.

2024-01-27 12:06 UTC, blademoon commented
@MKhalusova Good afternoon, Maria. When you recover, can you help us with this problem please?

2024-01-28 08:49 UTC, blademoon commented
@pdumin I may have found the problem. See how the `_toctree.yml` file looks like in the English version of the documentation:

<img width="413" alt="image" src="https://github.com/huggingface/course/assets/17560478/f0f326e6-1998-4630-b181-8827c6a47400">

In this PR, your file in the same section looks like this:

<img width="466" alt="image" src="https://github.com/huggingface/course/assets/17560478/190030b2-1d70-46d1-9104-e6ff9d1a9172">

It's supposed to look like this:

<img width="466" alt="image" src="https://github.com/huggingface/course/assets/17560478/66193140-2325-413e-90c2-27c7a6dd6f6f">

2024-01-28 08:52 UTC, blademoon commented
#75

2024-01-29 19:14 UTC, MKhalusova commented
Please run `make style` locally to fix the quality check.

2024-01-29 19:34 UTC, blademoon requested changes
@pdumin  Once again pointed out the area where the error that may break the documentation build. Try to fix.

2024-01-29 20:00 UTC, MKhalusova commented on chapters/ru/chapter8/4.mdx
> +При отладке обучения всегда нужно смотреть на декодированные входы модели. Мы не можем понять смысл чисел, которые подаем ей напрямую, поэтому мы должны посмотреть, что эти числа представляют. В комп
```suggestion
При отладке обучения всегда нужно смотреть на декодированные входы модели. Мы не можем понять смысл чисел, которые подаем ей напрямую, поэтому мы должны посмотреть, что эти числа представляют. В компьютерном зрении, например, это означает просмотр декодированных изображений пройденных пикселей, в речи - прослушивание декодированных образцов звука, а в нашем примере с NLP - использование нашего токенизатора для декодирования входных данных:
```

2024-01-29 20:07 UTC, MKhalusova commented on chapters/ru/chapter8/4.mdx
> +Опять же, если вы используете оптимизатор по умолчанию в `Trainer`, вы не должны получить ошибку на этом этапе, но если вы используете пользовательский оптимизатор, здесь могут возникнуть некоторые п
```suggestion
Опять же, если вы используете оптимизатор по умолчанию в `Trainer`, вы не должны получить ошибку на этом этапе, но если вы используете собственный оптимизатор, здесь могут возникнуть некоторые проблемы для отладки. Не забудьте вернуться к процессору, если на этом этапе вы получите странную ошибку CUDA. Говоря об ошибках CUDA, ранее мы упоминали особый случай. Давайте посмотрим на него сейчас.
```

2024-01-29 20:08 UTC, MKhalusova commented on chapters/ru/chapter8/4.mdx
> +# This will take a long time and error out, so you shouldn't run this cell
Please translate the code comment

2024-01-29 20:10 UTC, MKhalusova commented on chapters/ru/chapter8/4.mdx
> +Наши предсказания все еще являются логарифмами, а не реальными предсказаниями, поэтому метрика возвращает эту (несколько непонятную) ошибку. Исправить это довольно просто: нужно просто добавить argma
```suggestion
Наши предсказания все еще являются логитами, а не реальными предсказаниями, поэтому метрика возвращает эту (несколько непонятную) ошибку. Исправить это довольно просто: нужно просто добавить argmax в функцию `compute_metrics()`:
```

2024-01-29 20:24 UTC, MKhalusova commented on chapters/ru/chapter8/4.mdx
> +Настройка гиперпараметров всегда считается самой сложной частью машинного обучения, но это всего лишь последний шаг, который поможет вам немного улучшить метрику. В большинстве случаев гиперпараметры
```suggestion
Настройка гиперпараметров всегда считается самой сложной частью машинного обучения, но это всего лишь последний шаг, который поможет вам немного улучшить метрику. В большинстве случаев гиперпараметры по умолчанию `Trainer` будут работать нормально и давать вам хорошие результаты, поэтому не приступайте к трудоемкому и дорогостоящему поиску гиперпараметров, пока у вас не будет чего-то, что превосходит базовый уровень, который у вас есть в вашем наборе данных. 
```

2024-01-29 20:24 UTC, MKhalusova commented on chapters/ru/chapter8/4.mdx
> +### Попросить о помощи[[ask-for-help]]
```suggestion
### Попросите о помощи[[ask-for-help]]
```

2024-01-29 20:28 UTC, MKhalusova commented on chapters/ru/chapter8/5.mdx
> +Если вы столкнулись с чем-то, что кажется неправильным в одной из библиотек Hugging Face, вы должны обязательно сообщить нам об этом, чтобы мы могли это исправить (то же самое касается любой библиоте
```suggestion
Если вы столкнулись с чем-то, что кажется неправильным в одной из библиотек Hugging Face, обязательно сообщите нам об этом, чтобы мы могли это исправить (то же самое касается любой библиотеки с открытым исходным кодом, если на то пошло). Если вы не уверены, где именно кроется ошибка - в вашем собственном коде или в одной из наших библиотек, - первым делом загляните на [форумы](https://discuss.huggingface.co/). Сообщество поможет вам разобраться в этом, а команда Hugging Face также внимательно следит за обсуждениями там.
```

2024-01-30 15:46 UTC, MKhalusova commented
> The `make style` report is attached below, the problem persists. Suggested fixes have been made.
> 
> ```
> >> make style chapters/ru/chapter8/*
> python utils/code_formatter.py
> make: Nothing to be done for `chapters/ru/chapter8/1.mdx'.
> make: Nothing to be done for `chapters/ru/chapter8/2.mdx'.
> make: Nothing to be done for `chapters/ru/chapter8/3.mdx'.
> make: Nothing to be done for `chapters/ru/chapter8/4.mdx'.
> make: Nothing to be done for `chapters/ru/chapter8/4_tf.mdx'.
> make: Nothing to be done for `chapters/ru/chapter8/5.mdx'.
> make: Nothing to be done for `chapters/ru/chapter8/6.mdx'.
> make: Nothing to be done for `chapters/ru/chapter8/7.mdx'.
> ```


From what I see, `make style` fails on the CI/CD. I suspect that you need to update the dependencies in your local env, can you try this?

2024-01-30 15:53 UTC, pdumin commented
> > The `make style` report is attached below, the problem persists. Suggested fixes have been made.
> > ```
> > >> make style chapters/ru/chapter8/*
> > python utils/code_formatter.py
> > make: Nothing to be done for `chapters/ru/chapter8/1.mdx'.
> > make: Nothing to be done for `chapters/ru/chapter8/2.mdx'.
> > make: Nothing to be done for `chapters/ru/chapter8/3.mdx'.
> > make: Nothing to be done for `chapters/ru/chapter8/4.mdx'.
> > make: Nothing to be done for `chapters/ru/chapter8/4_tf.mdx'.
> > make: Nothing to be done for `chapters/ru/chapter8/5.mdx'.
> > make: Nothing to be done for `chapters/ru/chapter8/6.mdx'.
> > make: Nothing to be done for `chapters/ru/chapter8/7.mdx'.
> > ```
> 
> From what I see, `make style` fails on the CI/CD. I suspect that you need to update the dependencies in your local env, can you try this?

The dependencies is up to date, I installed them three days ago.

2024-01-30 20:02 UTC, MKhalusova commented on chapters/ru/_toctree.yml
> +-title: 8. Как попросить о помощи
```suggestion
- title: 8. Как попросить о помощи
```

2024-01-31 08:32 UTC, lewtun commented
Hello @pdumin I think this might be caused by a conflict of `black` versions in `requirements.txt` vs the unpinned version in the CI. I've opened a PR to relax this and once it's merged can you rebase on `main` and try running `make style` again please (after bumping your `black` version)?

2024-01-31 12:24 UTC, blademoon commented
@lewtun Thanks. This realy solve problem in #670.

2024-01-31 13:58 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/course/pr_667). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-01-31 14:03 UTC, pdumin commented
It worked. Thanks @blademoon @MKhalusova @lewtun

2024-01-31 14:14 UTC, blademoon commented
@pdumin You're welcome)))

2024-01-31 14:46 UTC, MKhalusova reviewed
Almost ready to merge! Spotted a couple of minor formatting issues and one untranslated paragraph.

2024-01-31 14:46 UTC, MKhalusova commented on chapters/ru/chapter8/2.mdx
> +or in a terminal:
```suggestion
или в терминале:
```

2024-01-31 14:46 UTC, MKhalusova commented on chapters/ru/chapter8/2.mdx
> +В этих отчетах содержится много информации, поэтому давайте вместе пройдемся по ключевым местам. Первое, что следует отметить, - это то, что трассировки следует читать _снизу вверх_. Это может показа
```suggestion
В этих отчетах содержится много информации, поэтому давайте вместе пройдемся по ключевым местам. Первое, что следует отметить, - это то, что трассировки следует читать _снизу вверх_. Это может показаться странным, если вы привыкли читать английский текст сверху вниз, но это логично: трассировка показывает последовательность вызовов функций, которые делает `pipeline` при загрузке модели и токенизатора. (Более подробно о том, как работает `pipeline` под капотом, читайте в [Главе 2](../chapter2/1)).
```

2024-01-31 14:46 UTC, MKhalusova commented on chapters/ru/chapter8/2.mdx
> +Здесь чтение сообщения об ошибке говорит нам, что у объекта `'list'' нет атрибута 'size', и мы видим стрелку `-->`, указывающую на строку, где возникла проблема в `model(**inputs)`. Вы можете отладит
```suggestion
Здесь чтение сообщения об ошибке говорит нам, что у объекта `'list'` нет атрибута 'size', и мы видим стрелку `-->`, указывающую на строку, где возникла проблема в `model(**inputs)`. Вы можете отладить это интерактивно, используя отладчик Python, но сейчас мы просто распечатаем фрагмент `inputs`, чтобы посмотреть, что у нас есть:
```

2024-01-31 14:46 UTC, MKhalusova commented on chapters/ru/chapter8/3.mdx
> +As you can see in the screenshot, enclosing the code blocks in backticks converts the raw text into formatted code, complete with color styling! Also note that single backticks can be used to format
This block is not translated.

2024-01-31 14:46 UTC, MKhalusova commented on chapters/ru/chapter8/4_tf.mdx
> +Здесь что-нибудь выделяется? Правильно - скорость обучения! Когда мы просто используем строку `'adam'', мы получим скорость обучения по умолчанию, которая составляет 0.001, или 1e-3. Это слишком мног
```suggestion
Здесь что-нибудь выделяется? Правильно - скорость обучения! Когда мы просто используем строку `'adam'`, мы получим скорость обучения по умолчанию, которая составляет 0.001, или 1e-3. Это слишком много для модели трансформера! В целом, мы рекомендуем использовать для моделей скорость обучения от 1e-5 до 1e-4; это в 10-100 раз меньше, чем значение, которое мы используем в данном случае. Похоже, это может стать серьезной проблемой, так что давайте попробуем ее уменьшить. Для этого нам нужно импортировать настоящий объект `optimizer`. Пока мы это делаем, давайте заново инициализируем модель из контрольной точки, на случай если обучение с высокой скоростью обучения повредило ее веса:
```

2024-01-31 17:26 UTC, MKhalusova approved these changes
Great work!

2024-01-31 17:26 UTC, merged

2024-01-31 17:48 UTC, blademoon commented
@lewtun @MKhalusova @pdumin Now it's my turn?)))